import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Providers } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Developer Gabriel Rieff",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  sheet
}: Readonly<{
  children: React.ReactNode;
  sheet: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased flex justify-center`}>
        <Providers>
          {children}
        </Providers>
          {sheet}
      </body>
    </html>
  );
}
